//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTale_Generator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTable_GeneratorEntities : DbContext
    {
        public TimeTable_GeneratorEntities()
            : base("name=TimeTable_GeneratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_faculty> tbl_faculty { get; set; }
        public virtual DbSet<tbl_lab> tbl_lab { get; set; }
        public virtual DbSet<tbl_subject> tbl_subject { get; set; }
    }
}
