//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTale_Generator
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_faculty
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string NAME { get; set; }
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string EMAIL { get; set; }
        [Required]
        [DataType(DataType.Password, ErrorMessage = "Password is not valid")]
        public string PASSWORD { get; set; }
        [Required]
        public string MOBILE_NO { get; set; }
        [Required]
        public string DESIGNATION { get; set; }
        [Required]
        [StringLength(5)]
        public string ALIAS { get; set; }
    }
}

