//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTale_Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lab
    {
        public int ID { get; set; }
        public Nullable<bool> ISLAB { get; set; }
        public string LAB_TYPE { get; set; }
        public string ADDITIONAL_DETAILS { get; set; }
        public string LOCATION { get; set; }
    }
}
