//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTale_Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subject
    {
        public int ID { get; set; }
        public string SUBJECT_NAME { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string COURSE_TYPE { get; set; }
        public Nullable<int> SUBJECT_CREDIT { get; set; }
        public Nullable<int> SEMESTER { get; set; }
    }
}
